# ------------------------ #
#      Novis Configs       #
# ------------------------ #
url: http://novisutd.com
title: Novis

youtube_videos:
  - id: dsXKXqiibW8
    title: Run to You
  - id: F3S-h2FUisU
    title: Pompeii
  - id: OqUdTXzvGwY
    title: Hey Soul Sister
  - id: hxSulj0xvcc
    title: Kaleidoscope Heart

banner_pictures:
  - /images/concertSpring2015.jpg
  - /images/novisPiano.jpg

banner_text: |
  UT Dallas's premier a cappella ensemble, Novis is the leading definition of
  new direction: completely student-run and performing compositions by
  university students. They perform a variety of modern a cappella music at
  concerts and events, both on and off campus. Novis is currently directed by
  Julia Burroughs.

upcoming_event: Fall audition date coming soon!

contact:
  president:
    name: Brendan Caseria
    email: novis@novisutd.com
  director:
    name: Julia Burroughs
    email: jjb130130@utdallas.edu
  social:
    name: Eric Dilmore & Frankie Imperial
    email: social@novisutd.com
  advisor:
    name: Kathryn Evans
    email: kcevans@utdallas.edu

member_current:
  - name: Natsumi Bailey
    part: Soprano
  - name: Julia Burroughs
    part: Soprano
  - name: Jeanette George
    part: Soprano
  - name: Shelby Koenig
    part: Soprano
  - name: Ruchi Kumar
    part: Alto
  - name: Mckena Roberts
    part: Alto
  - name: Peter Wynne
    part: Tenor
  - name: Frankie Imperial
    part: Tenor
  - name: Costa Skevofilax
    part: Tenor
  - name: Robert Beisert
    part: Bass
  - name: Brendan Caseria
    part: Bass
  - name: Eric Dilmore
    part: Bass
  - name: Philip Ross
    part: Bass
  - name: Ryan Scott
    part: Bass

member_alumni:
  - name: Jerry Li
    year: 2009
  - name: Braden Herndon
    year: 2009
  - name: Chana Pickett
    year: 2009
  - name: Brittany Farrel
    year: 2009
  - name: Kara Ragland
    year: 2009
  - name: Jackie Smith
    year: 2009
  - name: Andrew Pham
    year: 2009
  - name: Rebecca Rodda
    year: 2009
  - name: Jason Rodda
    year: 2009
  - name: Ruben Rosales
    year: 2010
  - name: Austin Atherton
    year: 2010
  - name: Rachael Bernstein
    year: 2010
  - name: Daniel Gonzales
    year: 2010
  - name: Brian Hernandez
    year: 2010
  - name: Sara Arnold
    year: 2010
  - name: Emily Bowersox
    year: 2010
  - name: Mark Cordell
    year: 2011
  - name: Emily McCoy
    year: 2011
  - name: Apoorva Anupindi
    year: 2012
  - name: Michael Shell
    year: 2012
  - name: Elizabeth Petruy
    year: 2012
  - name: Emily Becker
    year: 2012
  - name: Caleb Phillips
    year: 2012
  - name: Claire Bruce
    year: 2012
  - name: Sharon Jacob
    year: 2012
  - name: Emily Trusky
    year: 2012
  - name: Riley Firth
    year: 2012
  - name: Caitlin Morrow
    year: 2012
  - name: Victoria Aranda
    year: 2013
  - name: Alex Luna
    year: 2013
  - name: Eli Aalderink
    year: 2013
  - name: Andrew McCament
    year: 2014
  - name: Abigail Madsen
    year: 2014
  - name: Casey Sublet
    year: 2014
  - name: Julia Pauletti
    year: 2014
  - name: Priya Matthew
    year: 2014
  - name: Franklin Co
    year: 2014
  - name: Kristina Arnst
    year: 2014
  - name: Morgan Stone
    year: 2014
  - name: Sammy Lutes
    year: 2014
  - name: Mark SanGiorgio
    year: 2014
  - name: Melania Amaya
    year: 2014
  - name: Albert Ok
    year: 2014

repertoire:
  - name: Novis Nerdfest 2.0
    songs:
      - title: Banelings
        arranger: HuskyStarcraft / Kurt Schneider
      - title: Double Trouble
        arranger: Harry Potter and the Prizoner of Azkaban
      - title: Dramatic Song
        arranger: Toby Turner
      - title: This is Halloween
        arranger: The Nightmare Before Christmas
      - title: Theme from Halo / Finish the Fight
        arranger: Andrew Mitchell
      - title: Lights
        arranger: Ellie Goulding
      - title: May It Be
        arranger: The Lord of the Rings: The Fellowship of the Ring
      - title: Sons of Skyrim
        arranger: The Elder Scrolls V: Skyrim
      - title: Spooky
        arranger: as performed by Imogen Heap
  - name: Novis Bash 2011
    songs:
      - title: Alice in Wonderland 
        youtube: http://www.youtube.com/watch?v=BKyYpkktUw4
      - title: Hey, Soul Sister 
        youtube: http://www.youtube.com/watch?v=WPijUA_t9iI
        arranger: Train
      - title: Listen to the Music 
        youtube: http://www.youtube.com/watch?v=qrXVSfrlTrE
        arranger: The Doobie Brothers
      - title: Magic 
        youtube: http://www.youtube.com/watch?v=LLp4SAbK45s
        arranger: Ben Folds
      - title: Rolling in the Deep 
        youtube: http://www.youtube.com/watch?v=l-mqW6JGk8w
        arranger: Adele
  - name: Peace, Love, 'n Harmony
    songs:
      - title: I Got You (I Feel Good)
        arranger: James Brown
      - title: My Girl
        arranger: The Temptations
      - title: Blackbird
        arranger: The Beatles
      - title: Kiss From a Rose 
        youtube: http://www.youtube.com/watch?v=d-cDVcd6blI
        arranger: Seal
      - title: All You Need is Love
        arranger: The Beatles
      - title: Hey, Soul Sister 
        youtube: http://www.youtube.com/watch?v=WPijUA_t9iI
        arranger: Train
      - title: Halo 
        youtube: http://www.youtube.com/watch?v=SRfuzf3O6AM
        arranger: Beyonce
      - title: Somebody to Love
        arranger: Queen
      - title: Fireflies
        arranger: Owl City
      - title: I Kissed a Girl
        arranger: Katy Perry
      - title: Walking on Sunshine
        arranger: Katrina and the Waves
      - title: Title of the Song 
        youtube: http://www.youtube.com/watch?v=734wnHnnNR4
        arranger: Da Vinci's Notebook
  - name: Novis Sings Walt Disney
    songs:
      - title: Be Prepared 
        youtube: http://www.youtube.com/watch?v=FA2JUgEsTgI
        arranger: The Lion King
      - title: Can You Feel the Love Tonight
        arranger: The Lion King
      - title: Everybody Wants to be a Cat 
        youtube: http://www.youtube.com/watch?v=Kgt6dm9dugc
        arranger: The Aristocats
      - title: God Help the Outcasts 
        youtube: http://www.youtube.com/watch?v=eDbSYNKrDrE
        arranger: The Hunchback of Notre Dame
      - title: Go the Distance 
        youtube: http://www.youtube.com/watch?v=py6Xu77lpB8
        arranger: Hercules
      - title: Hakuna Matata
        arranger: The Lion King
      - title: I Wanna Be Like You 
        youtube: http://www.youtube.com/watch?v=CjK4AqxFgZw
        arranger: The Jungle Book
      - title: I Won't Say I'm in Love 
        youtube: http://www.youtube.com/watch?v=BCgtZZlje0o
        arranger: Hercules
      - title: Kiss the Girl 
        youtube: http://www.youtube.com/watch?v=AZBeBdsfx4E
        arranger: The Little Mermaid
      - title: Seize the Day 
        youtube: http://www.youtube.com/watch?v=fcngHD_zL14
        arranger: Newsies
      - title: Under the Sea
        arranger: The Little Mermaid
      - title: Zero to Hero
        youtube: http://www.youtube.com/watch?v=ylhVkDfS-TE
        arranger: Hercules
  - name: Novis: A Night At the Movies
    songs:
      - title: Because
        arranger: Across The Universe (Beatles)
      - title: My Freeze Ray / A Man's Gotta Do
        arranger: Dr. Horrible's Sing-Along Blog
      - title: Eye of The Tiger
        arranger: Frankie Sullivan
      - title: Goin' Back To Hogwarts
        arranger: A Very Potter Musical
      - title: Moon River
        arranger: Steve Zegree
      - title: Time Warp
        arranger: The Rocky Horror Picture Show
      - title: The Grid / The Game Has Changed
        arranger: Walt Disney's Tron: Legacy
  - name: Novis Nerdfest
    songs:
      - title: Cartoon Medley
        youtube: http://www.youtube.com/watch?v=45pE2wthPCk
        arranger: Andrew Mitchell
      - title: Do You Wanna Date My Avatar 
        youtube: http://www.youtube.com/watch?v=IgRKmeK3uZA
        arranger: The Guild
      - title: John Williams is the Man 
        youtube: http://www.youtube.com/watch?v=wTuIIIcwNn8
        arranger: Moosebutter
      - title: Pokemon Theme 
        youtube: http://www.youtube.com/watch?v=7-5WvSt2pdo
        arranger: Siegler, Loeffler
      - title: Portal Medley 
        youtube: http://www.youtube.com/watch?v=LUY086gY6Ls
        arranger: Eli Aalderink
      - title: Sci-Fi Medley 
        youtube: http://www.youtube.com/watch?v=ht24mZ7W_r4
        arranger: Andrew Mitchell
  - name: Novis Bash 2010
    songs:
      - title: Bad Romance
        arranger: Lady Gaga
      - title: Beautiful
        arranger: Christina Aguilera
      - title: Hide and Seek
        arranger: Imogen Heap
      - title: I Gotta Feeling
        arranger: Black Eyed Peas
      - title: Kryptonite
        arranger: 3 Doors Down
      - title: Live Like We're Dying
        arranger: Kris Allen
      - title: Low
        arranger: Flo Rida
      - title: My Life Would suck Without You
        arranger: Kelly Clarkson
      - title: Suddenly I See
        arranger: KT Tunstall
      - title: Viva la Vida
        arranger: Coldplay
  - name: Novis Rocks the 80's
    songs:
      - title: And So It Goes
        arranger: Billy Joel
      - title: Don't Stop Believing 
        youtube: http://www.youtube.com/watch?v=b083Yx2a_DE
        arranger: Journey
      - title: Jessie's Girl
        arranger: Rick Springfield
      - title: Manic Monday
        arranger: The Bangles
      - title: Video Killed the Radio Star
        arranger: The Buggles

# ----------------------- #
#      Main Configs       #
# ----------------------- #
simple_search: https://www.google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: NovisUTD
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false
